export { default as XInput } from "./xInput"
export { default as XSubmit } from "./xSubmit"
export { default as XLoading } from "./xLoading"
export { default as XAlert } from "./xAlert"
export { default as XColored } from "./xColored"
export { default as XAlertDialog } from "./xAlertDialog"
export { default as XDialog } from "./xDialog"
export * from "./Dashboard"
