export { default as Home } from "./Home"
export { default as LoginBikerPage } from "./loginBiker"
export { default as LoginCustomerPage } from "./loginCustomer"
export { default as Dashboard } from "./Dashboard"
export { default as NewShipmentPage } from "./Dashboard/newShipment"
